version: '3.2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    #ports:
     # - '8080:8080'
    volumes:
      - .:/app
    command: 'make dev'
  
  caddy:
    image: caddy:latest
    restart: unless-stopped
    depends_on: 
      - app 
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./services/caddy:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
