name: ci

on:
  push:
      branches:
        - 'master'
env:
  LATEST_TAG:  ${{ secrets.DOCKERHUB_USERNAME }}/docker-project-74:latest
  TEST_TAG:  ${{ secrets.DOCKERHUB_USERNAME }}/docker-project-74:test
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run tests
        run: POSTGRES_USER=${{secrets.DATABASE_USERNAME}} POSTGRES_PASSWORD=${{ secrets.DATABASE_PASSWORD }} POSTGRES_HOST=${{ secrets.DATABASE_HOST }} docker compose -f app/docker-compose.yml up --abort-on-container-exit  
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      # Заливаем протестированный образ на Docker Hub
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: app/
          file: app/Docker.production
          push: true
          tags: ${{ env.LATEST_TAG }}
        
